In [85]:
import pandas as pd
import plotly.express as px
import streamlit as st

In [106]:
df=pd.read_csv('taxi_sample.csv')
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,Zone_dropoff,service_zone_dropoff,year,month,day,hour_pickup,hour_pickup_min,hour_dropoff,trip_duration_minutes,day_period
0,2,2024-08-12 08:27:44,2024-08-12 08:45:28,1,1.69,1.000000,N,161,237,Credit card,...,Upper East Side South,Yellow Zone,2024,August,Monday,8,08:27,08:45,17.733333,Morining
1,2,2024-08-10 01:02:50,2024-08-10 01:08:10,1,0.74,1.000000,N,79,45,Credit card,...,Chinatown,Yellow Zone,2024,August,Saturday,1,01:02,01:08,5.333333,Night
2,2,2024-06-07 15:48:46,2024-06-07 15:52:59,5,0.47,1.000000,N,231,231,Cash,...,TriBeCa/Civic Center,Yellow Zone,2024,June,Friday,15,15:48,15:52,4.216667,Afternoon
3,2,2024-03-27 13:40:48,2024-03-27 14:06:11,1,5.04,1.000000,N,230,261,Credit card,...,World Trade Center,Yellow Zone,2024,March,Wednesday,13,13:40,14:06,25.383333,Afternoon
4,2,2024-05-19 10:37:00,2024-05-19 10:50:24,3,2.22,1.000000,N,162,79,Credit card,...,East Village,Yellow Zone,2024,May,Sunday,10,10:37,10:50,13.400000,Morining
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19347,1,2024-03-07 06:57:34,2024-03-07 07:05:30,1,1.90,1.000000,N,68,161,Credit card,...,Midtown Center,Yellow Zone,2024,March,Thursday,6,06:57,07:05,7.933333,Morining
19348,1,2024-03-12 09:38:33,2024-03-12 09:44:14,1,0.30,1.000000,N,163,161,Credit card,...,Midtown Center,Yellow Zone,2024,March,Tuesday,9,09:38,09:44,5.683333,Morining
19349,1,2024-02-20 14:07:41,2024-02-20 14:21:40,1,3.30,1.000000,N,140,164,Credit card,...,Midtown South,Yellow Zone,2024,February,Tuesday,14,14:07,14:21,13.983333,Afternoon
19350,2,2024-05-16 16:01:32,2024-05-16 16:09:58,1,0.80,1.000000,N,161,164,Credit card,...,Midtown South,Yellow Zone,2024,May,Thursday,16,16:01,16:09,8.433333,Afternoon
19351,2,2024-03-25 20:52:47,2024-03-25 21:09:02,1,2.76,2.304215,N,140,238,Flex Fare trip,...,Upper West Side North,Yellow Zone,2024,March,Monday,20,20:52,21:09,16.250000,Evening

In [107]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,Zone_dropoff,service_zone_dropoff,year,month,day,hour_pickup,hour_pickup_min,hour_dropoff,trip_duration_minutes,day_period
0,2,2024-08-12 08:27:44,2024-08-12 08:45:28,1,1.69,1.000000,N,161,237,Credit card,...,Upper East Side South,Yellow Zone,2024,August,Monday,8,08:27,08:45,17.733333,Morining
1,2,2024-08-10 01:02:50,2024-08-10 01:08:10,1,0.74,1.000000,N,79,45,Credit card,...,Chinatown,Yellow Zone,2024,August,Saturday,1,01:02,01:08,5.333333,Night
2,2,2024-06-07 15:48:46,2024-06-07 15:52:59,5,0.47,1.000000,N,231,231,Cash,...,TriBeCa/Civic Center,Yellow Zone,2024,June,Friday,15,15:48,15:52,4.216667,Afternoon
3,2,2024-03-27 13:40:48,2024-03-27 14:06:11,1,5.04,1.000000,N,230,261,Credit card,...,World Trade Center,Yellow Zone,2024,March,Wednesday,13,13:40,14:06,25.383333,Afternoon
4,2,2024-05-19 10:37:00,2024-05-19 10:50:24,3,2.22,1.000000,N,162,79,Credit card,...,East Village,Yellow Zone,2024,May,Sunday,10,10:37,10:50,13.400000,Morining
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19347,1,2024-03-07 06:57:34,2024-03-07 07:05:30,1,1.90,1.000000,N,68,161,Credit card,...,Midtown Center,Yellow Zone,2024,March,Thursday,6,06:57,07:05,7.933333,Morining
19348,1,2024-03-12 09:38:33,2024-03-12 09:44:14,1,0.30,1.000000,N,163,161,Credit card,...,Midtown Center,Yellow Zone,2024,March,Tuesday,9,09:38,09:44,5.683333,Morining
19349,1,2024-02-20 14:07:41,2024-02-20 14:21:40,1,3.30,1.000000,N,140,164,Credit card,...,Midtown South,Yellow Zone,2024,February,Tuesday,14,14:07,14:21,13.983333,Afternoon
19350,2,2024-05-16 16:01:32,2024-05-16 16:09:58,1,0.80,1.000000,N,161,164,Credit card,...,Midtown South,Yellow Zone,2024,May,Thursday,16,16:01,16:09,8.433333,Afternoon
19351,2,2024-03-25 20:52:47,2024-03-25 21:09:02,1,2.76,2.304215,N,140,238,Flex Fare trip,...,Upper West Side North,Yellow Zone,2024,March,Monday,20,20:52,21:09,16.250000,Evening

## Deployment

In [ ]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'LocationID_pickup', 'Borough_pickup', 'Zone_pickup',
       'service_zone_pickup', 'LocationID_dropoff', 'Borough_dropoff',
       'Zone_dropoff', 'service_zone_dropoff', 'year', 'month', 'day',
       'hour_pickup', 'hour_pickup_min', 'hour_dropoff', 'day_period'],
      dtype='object')

In [108]:
df.select_dtypes('number')

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,LocationID_pickup,LocationID_dropoff,year,hour_pickup,trip_duration_minutes
0,2,1,1.69,1.000000,161,237,16.30,0.0,0.5,1.00,0.0,1.0,21.30,2.5,0.0,161,237,2024,8,17.733333
1,2,1,0.74,1.000000,79,45,7.20,1.0,0.5,3.05,0.0,1.0,15.25,2.5,0.0,79,45,2024,1,5.333333
2,2,5,0.47,1.000000,231,231,5.80,0.0,0.5,0.00,0.0,1.0,9.80,2.5,0.0,231,231,2024,15,4.216667
3,2,1,5.04,1.000000,230,261,28.90,0.0,0.5,6.00,0.0,1.0,38.90,2.5,0.0,230,261,2024,13,25.383333
4,2,3,2.22,1.000000,162,79,14.90,0.0,0.5,4.72,0.0,1.0,23.62,2.5,0.0,162,79,2024,10,13.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19347,1,1,1.90,1.000000,68,161,10.70,2.5,0.5,2.90,0.0,1.0,17.60,2.5,0.0,68,161,2024,6,7.933333
19348,1,1,0.30,1.000000,163,161,5.80,2.5,0.5,0.00,0.0,1.0,9.80,2.5,0.0,163,161,2024,9,5.683333
19349,1,1,3.30,1.000000,140,164,17.70,2.5,0.5,5.40,0.0,1.0,27.10,2.5,0.0,140,164,2024,14,13.983333
19350,2,1,0.80,1.000000,161,164,8.60,0.0,0.5,2.52,0.0,1.0,15.12,2.5,0.0,161,164,2024,16,8.433333
19351,2,1,2.76,2.304215,140,238,17.81,0.0,0.5,0.00,0.0,1.0,21.81,0.0,0.0,140,238,2024,20,16.250000

In [109]:
df.select_dtypes('O')

,tpep_pickup_datetime,tpep_dropoff_datetime,store_and_fwd_flag,payment_type,Borough_pickup,Zone_pickup,service_zone_pickup,Borough_dropoff,Zone_dropoff,service_zone_dropoff,month,day,hour_pickup_min,hour_dropoff,day_period
0,2024-08-12 08:27:44,2024-08-12 08:45:28,N,Credit card,Manhattan,Midtown Center,Yellow Zone,Manhattan,Upper East Side South,Yellow Zone,August,Monday,08:27,08:45,Morining
1,2024-08-10 01:02:50,2024-08-10 01:08:10,N,Credit card,Manhattan,East Village,Yellow Zone,Manhattan,Chinatown,Yellow Zone,August,Saturday,01:02,01:08,Night
2,2024-06-07 15:48:46,2024-06-07 15:52:59,N,Cash,Manhattan,TriBeCa/Civic Center,Yellow Zone,Manhattan,TriBeCa/Civic Center,Yellow Zone,June,Friday,15:48,15:52,Afternoon
3,2024-03-27 13:40:48,2024-03-27 14:06:11,N,Credit card,Manhattan,Times Sq/Theatre District,Yellow Zone,Manhattan,World Trade Center,Yellow Zone,March,Wednesday,13:40,14:06,Afternoon
4,2024-05-19 10:37:00,2024-05-19 10:50:24,N,Credit card,Manhattan,Midtown East,Yellow Zone,Manhattan,East Village,Yellow Zone,May,Sunday,10:37,10:50,Morining
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19347,2024-03-07 06:57:34,2024-03-07 07:05:30,N,Credit card,Manhattan,East Chelsea,Yellow Zone,Manhattan,Midtown Center,Yellow Zone,March,Thursday,06:57,07:05,Morining
19348,2024-03-12 09:38:33,2024-03-12 09:44:14,N,Credit card,Manhattan,Midtown North,Yellow Zone,Manhattan,Midtown Center,Yellow Zone,March,Tuesday,09:38,09:44,Morining
19349,2024-02-20 14:07:41,2024-02-20 14:21:40,N,Credit card,Manhattan,Lenox Hill East,Yellow Zone,Manhattan,Midtown South,Yellow Zone,February,Tuesday,14:07,14:21,Afternoon
19350,2024-05-16 16:01:32,2024-05-16 16:09:58,N,Credit card,Manhattan,Midtown Center,Yellow Zone,Manhattan,Midtown South,Yellow Zone,May,Thursday,16:01,16:09,Afternoon
19351,2024-03-25 20:52:47,2024-03-25 21:09:02,N,Flex Fare trip,Manhattan,Lenox Hill East,Yellow Zone,Manhattan,Upper West Side North,Yellow Zone,March,Monday,20:52,21:09,Evening

In [ ]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,Borough_dropoff,Zone_dropoff,service_zone_dropoff,year,month,day,hour_pickup,hour_pickup_min,hour_dropoff,day_period
0,2,2024-08-12 08:27:44,2024-08-12 08:45:28,1.0,1.69,1.0,N,161,237,1,...,Manhattan,Upper East Side South,Yellow Zone,2024,August,Monday,8,08:27,08:45,Morining
1,2,2024-08-10 01:02:50,2024-08-10 01:08:10,1.0,0.74,1.0,N,79,45,1,...,Manhattan,Chinatown,Yellow Zone,2024,August,Saturday,1,01:02,01:08,Night
2,2,2024-06-07 15:48:46,2024-06-07 15:52:59,5.0,0.47,1.0,N,231,231,2,...,Manhattan,TriBeCa/Civic Center,Yellow Zone,2024,June,Friday,15,15:48,15:52,Afternoon
3,2,2024-03-27 13:40:48,2024-03-27 14:06:11,1.0,5.04,1.0,N,230,261,1,...,Manhattan,World Trade Center,Yellow Zone,2024,March,Wednesday,13,13:40,14:06,Afternoon
4,2,2024-05-19 10:37:00,2024-05-19 10:50:24,3.0,2.22,1.0,N,162,79,1,...,Manhattan,East Village,Yellow Zone,2024,May,Sunday,10,10:37,10:50,Morining

In [ ]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'LocationID_pickup', 'Borough_pickup', 'Zone_pickup',
       'service_zone_pickup', 'LocationID_dropoff', 'Borough_dropoff',
       'Zone_dropoff', 'service_zone_dropoff', 'year', 'month', 'day',
       'hour_pickup', 'hour_pickup_min', 'hour_dropoff', 'day_period'],
      dtype='object')

In [154]:
%%writefile Yellow_Taxi_Trip.py
import pandas as pd
import plotly.express as px
import streamlit as st


st.set_page_config(layout= 'wide', page_title= 'NYC Yellow Taxi Tript EDA')

html_title = """<h1 style="color:white;text-align:center;"> NYC Yellow Taxi Trip Exploratory Data Analysis </h1>"""
st.markdown(html_title, unsafe_allow_html=True)
st.image('dataset-cove3r.png')

df = pd.read_csv('taxi_sample.csv', index_col= 0)
df=df.sort_values(by='tpep_pickup_datetime')
page = st.sidebar.radio('Page', ["Home", "Univariate Analysis", "Trip Analysis", "Fare Revenue Analysis","Time Analysis","Passenger Insights"])
if page == "Home":

    # Dataframe
    st.subheader('Dataset Overview')
    st.dataframe(df)

    # Data Description
    column_descriptions = {
    "VendorID": "Code indicating the taxi provider or vendor for the trip.",
    "tpep_pickup_datetime": "Timestamp when the passenger was picked up.",
    "tpep_dropoff_datetime": "Timestamp when the passenger was dropped off.",
    "passenger_count": "Number of passengers in the taxi during the trip.",
    "trip_distance": "Distance traveled during the trip (in miles).",
    "RatecodeID": "Identifier for the rate type used for the trip fare.",
    "store_and_fwd_flag": "Flag indicating whether the trip record was stored and forwarded due to no network connection.",
    "PULocationID": "Pickup location ID as defined in the NYC taxi zones.",
    "DOLocationID": "Dropoff location ID as defined in the NYC taxi zones.",
    "payment_type": "Numeric code indicating the passenger’s payment method (e.g., card, cash).",
    "fare_amount": "Base fare charged for the trip before additional fees.",
    "extra": "Additional miscellaneous charges (e.g., surcharge, booking fees).",
    "mta_tax": "Mandatory $0.50 tax charged for all TPEP trips.",
    "tip_amount": "Tip amount provided by the passenger.",
    "tolls_amount": "Total tolls charged during the trip.",
    "improvement_surcharge": "Standard $0.30 improvement surcharge added to trips.",
    "congestion_surcharge": "Additional fee applied for congestion zones, if applicable.",
    "Airport_fee": "Fee applied when trips originate from or end at airports.",
    "total_amount": "Total amount charged to the passenger including all fees.",
    "LocationID_pickup": "Mapped pickup zone location ID.",
    "Borough_pickup": "Borough corresponding to the pickup location.",
    "Zone_pickup": "Specific zone name for the pickup location.",
    "service_zone_pickup": "Service zone (e.g., Yellow Zone, Green Zone) for the pickup.",
    "LocationID_dropoff": "Mapped dropoff zone location ID.",
    "Borough_dropoff": "Borough corresponding to the dropoff location.",
    "Zone_dropoff": "Specific zone name for the dropoff location.",
    "service_zone_dropoff": "Service zone (e.g., Yellow Zone, Green Zone) for the dropoff.",
    "year": "Year extracted from the pickup timestamp.",
    "month": "Month extracted from the pickup timestamp.",
    "day": "Day of the month extracted from the pickup timestamp.",
    "hour_pickup": "Hour of the day when the pickup occurred (24-hour format).",
    "hour_pickup_min": "Minute component of the pickup timestamp.",
    "hour_dropoff": "Hour of the day when the dropoff occurred (24-hour format).",
    "trip_duration_minutes": "Total trip duration measured in minutes.",
    "day_period": "Part of the day when the trip occurred (morning, afternoon, night, etc.)."}

    # Create a table for descriptions
    desc_df = pd.DataFrame(list(column_descriptions.items()), columns=["Column Name", "Description"])

    # Display table
    st.subheader("📝 Column Descriptions")
    st.table(desc_df)

elif page == "Univariate Analysis":

    st.title('Choose your Column and Chart')

    # Create Numerical and Categorical Tabs
    tab_num, tab_cat = st.tabs(['Numerical', 'Categorical'])

    # Select Numerical Column
    num_cols = df.select_dtypes(include= 'number').columns.drop(['RatecodeID','PULocationID','DOLocationID','LocationID_pickup','LocationID_dropoff'	])
    selected_num_col = tab_num.selectbox('Column', num_cols)

    # Select Chart
    tab_num.plotly_chart(px.histogram(data_frame = df, x = selected_num_col, title = selected_num_col, text_auto=True))


    # Select Catgorical Column
    cat_cols = df.select_dtypes(include= 'object').columns.drop(['tpep_pickup_datetime','tpep_dropoff_datetime'])
    selected_cat_col = tab_cat.selectbox('Column', cat_cols)


    # Select Chart
    selected_chart = tab_cat.selectbox('Chart', ['Bar', 'Pie'])

    if selected_chart == 'Bar':
        tab_cat.plotly_chart(px.histogram(data_frame = df, x = selected_cat_col, title = selected_cat_col).update_xaxes(categoryorder = 'max descending'))

    elif selected_chart == 'Pie':
        tab_cat.plotly_chart(px.pie(data_frame = df, names = selected_cat_col, title = selected_cat_col))

#####################################

elif page ==  "Trip Analysis":

    html_title = """<h1 style="color:white;text-align:center;"> Trip Analysis </h1>"""
    st.markdown(html_title, unsafe_allow_html=True)

    col1, col2, col3 = st.columns(3)

    col1.metric('Total Orders', df.LocationID_dropoff.nunique())
    col2.metric('Total Revenue', f'${df.fare_amount.sum()}')
    col3.metric('Total Customers', df.RatecodeID.nunique())


    st.subheader('📈 At what pickup hours do passengers tend to give higher tip amounts?”')
    pvt_tip_h=df.groupby(['hour_pickup'])['tip_amount'].mean().sort_values(ascending=False).reset_index().round(2)
    st.plotly_chart(px.bar( pvt_tip_h,
    x='hour_pickup',
    y='tip_amount',
    title='Average Tip Amount by Pickup Hour of tha day',
    text='tip_amount'
    ,color='hour_pickup'))

    st.subheader('Which boroughs have the longest average trip distances Based on Pickup Borough?')
    st.plotly_chart(px.histogram(data_frame=df, x='Borough_pickup', y='trip_distance', histfunc='avg', text_auto=True))

    st.header("15. Day of the week with highest average tip")
    avg_tip_day = df.groupby("day")["tip_amount"].mean()
    st.bar_chart(avg_tip_day)

    st.header("16. Part of day with highest average tip")
    avg_tip_period = df.groupby("day_period")["tip_amount"].mean()
    st.bar_chart(avg_tip_period)

    st.header("17. Total passengers per period each month")
    passengers_month_period = df.groupby(["month","day_period"])["passenger_count"].sum().unstack()
    st.bar_chart(passengers_month_period)

    st.header("18. Period with highest cash ratio proportion")
    cash_ratio = df[df["payment_type"]=="Cash"].groupby("day_period")["payment_type"].count() / df.groupby("day_period")["payment_type"].count()
    st.bar_chart(cash_ratio)


elif page == "Fare Revenue Analysis":
    st.title("Fare Revenue Analysis 💵")

    st.header("9. Average fare amount by day of the week")
    avg_fare_day = df.groupby("day")["fare_amount"].mean()
    st.bar_chart(avg_fare_day)

    st.header("10. Highest fare amounts per day")
    max_fare_day = df.groupby("day")["fare_amount"].max()
    st.bar_chart(max_fare_day)

    st.header("11. Total fare by month")
    fare_month = df.groupby("month")["fare_amount"].sum()
    st.bar_chart(fare_month)

    st.header("12. Highest average fare by period of the day")
    avg_fare_period = df.groupby("day_period")["fare_amount"].mean()
    st.bar_chart(avg_fare_period)

    st.header("13. Highest fare amount per payment type")
    max_fare_payment = df.groupby("payment_type")["fare_amount"].max()
    st.bar_chart(max_fare_payment)

# ---------------------------
# 3️⃣ Time Analysis
# ---------------------------
elif page == "Time Analysis":
    st.title("Time Analysis ⏰")

    st.header("14. Pickup hours vs Tip amount")
    tip_hour = df.groupby("hour_pickup")["tip_amount"].mean()
    st.line_chart(tip_hour)

    st.header("15. Day of the week with highest average tip")
    avg_tip_day = df.groupby("day")["tip_amount"].mean()
    st.bar_chart(avg_tip_day)

    st.header("16. Part of day with highest average tip")
    avg_tip_period = df.groupby("day_period")["tip_amount"].mean()
    st.bar_chart(avg_tip_period)

    st.header("17. Total passengers per period each month")
    passengers_month_period = df.groupby(["month","day_period"])["passenger_count"].sum().unstack()
    st.bar_chart(passengers_month_period)

    st.header("18. Period with highest cash ratio proportion")
    cash_ratio = df[df["payment_type"]=="Cash"].groupby("day_period")["payment_type"].count() / df.groupby("day_period")["payment_type"].count()
    st.bar_chart(cash_ratio)

# ---------------------------
# 4️⃣ Passenger Insights
# ---------------------------
elif page == "Passenger Insights":
    st.title("Passenger Insights 🧑‍🤝‍🧑")

    st.header("19. Total number of trips by passenger count")
    trips_per_passenger = df["passenger_count"].value_counts().sort_index()
    st.bar_chart(trips_per_passenger)

    st.header("20. Total amount paid vs passenger count")
    total_passenger = df.groupby("passenger_count")["fare_amount"].sum()
    st.bar_chart(total_passenger)

    st.header("21. Trips with more passengers tend to give higher tips")
    tip_passenger = df.groupby("passenger_count")["tip_amount"].mean()
    st.bar_chart(tip_passenger)

    st.header("22. Trip distance vs passenger count")
    distance_passenger = df.groupby("passenger_count")["trip_distance"].mean()
    st.bar_chart(distance_passenger)

    st.header("New Question: Average trip distance by passenger count")
    avg_distance_passenger = df.groupby("passenger_count")["trip_distance"].mean()
    st.bar_chart(avg_distance_passenger)

Overwriting Yellow_Taxi_Trip.py

In [155]:
! streamlit run Yellow_Taxi_Trip.py

^C

In [121]:
df=df.sort_values(by='tpep_pickup_datetime')
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,Zone_dropoff,service_zone_dropoff,year,month,day,hour_pickup,hour_pickup_min,hour_dropoff,trip_duration_minutes,day_period
2310,2,2024-01-01 00:03:12,2024-01-01 00:08:50,1,1.69,1.000000,N,141,263,Credit card,...,Yorkville West,Yellow Zone,2024,January,Monday,0,00:03,00:08,5.633333,Night
10003,2,2024-01-01 00:09:19,2024-01-01 00:21:34,1,1.79,1.000000,N,163,239,Cash,...,Upper West Side South,Yellow Zone,2024,January,Monday,0,00:09,00:21,12.250000,Night
16883,2,2024-01-01 00:09:32,2024-01-01 00:13:32,3,0.91,1.000000,N,140,140,Credit card,...,Lenox Hill East,Yellow Zone,2024,January,Monday,0,00:09,00:13,4.000000,Night
16590,1,2024-01-01 00:13:16,2024-01-01 00:28:41,1,3.50,1.000000,N,161,226,Credit card,...,Sunnyside,Boro Zone,2024,January,Monday,0,00:13,00:28,15.416667,Night
4490,1,2024-01-01 00:17:42,2024-01-01 00:32:10,1,0.50,2.304215,N,48,48,Flex Fare trip,...,Clinton East,Yellow Zone,2024,January,Monday,0,00:17,00:32,14.466667,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9071,1,2024-08-31 22:36:12,2024-08-31 22:54:17,1,3.40,1.000000,N,45,229,Credit card,...,Sutton Place/Turtle Bay North,Yellow Zone,2024,August,Saturday,22,22:36,22:54,18.083333,Night
13822,2,2024-08-31 22:39:36,2024-08-31 22:53:48,4,2.38,1.000000,N,87,90,Credit card,...,Flatiron,Yellow Zone,2024,August,Saturday,22,22:39,22:53,14.200000,Night
16448,2,2024-08-31 22:48:02,2024-08-31 23:07:20,1,3.30,1.000000,N,151,42,Credit card,...,Central Harlem North,Boro Zone,2024,August,Saturday,22,22:48,23:07,19.300000,Night
1338,2,2024-08-31 22:52:09,2024-08-31 23:06:33,1,1.50,1.000000,N,230,100,Credit card,...,Garment District,Yellow Zone,2024,August,Saturday,22,22:52,23:06,14.400000,Night
11782,2,2024-08-31 23:28:26,2024-08-31 23:54:57,3,9.76,1.000000,N,93,237,Credit card,...,Upper East Side South,Yellow Zone,2024,August,Saturday,23,23:28,23:54,26.516667,Night

In [91]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'LocationID_pickup', 'Borough_pickup', 'Zone_pickup',
       'service_zone_pickup', 'LocationID_dropoff', 'Borough_dropoff',
       'Zone_dropoff', 'service_zone_dropoff', 'year', 'month', 'day',
       'hour_pickup', 'hour_pickup_min', 'hour_dropoff', 'day_period'],
      dtype='object')

In [89]:
df.select_dtypes('O')

,tpep_pickup_datetime,tpep_dropoff_datetime,store_and_fwd_flag,Borough_pickup,Zone_pickup,service_zone_pickup,Borough_dropoff,Zone_dropoff,service_zone_dropoff,month,day,hour_pickup_min,hour_dropoff,day_period
0,2024-08-12 08:27:44,2024-08-12 08:45:28,N,Manhattan,Midtown Center,Yellow Zone,Manhattan,Upper East Side South,Yellow Zone,August,Monday,08:27,08:45,Morining
1,2024-08-10 01:02:50,2024-08-10 01:08:10,N,Manhattan,East Village,Yellow Zone,Manhattan,Chinatown,Yellow Zone,August,Saturday,01:02,01:08,Night
2,2024-06-07 15:48:46,2024-06-07 15:52:59,N,Manhattan,TriBeCa/Civic Center,Yellow Zone,Manhattan,TriBeCa/Civic Center,Yellow Zone,June,Friday,15:48,15:52,Afternoon
3,2024-03-27 13:40:48,2024-03-27 14:06:11,N,Manhattan,Times Sq/Theatre District,Yellow Zone,Manhattan,World Trade Center,Yellow Zone,March,Wednesday,13:40,14:06,Afternoon
4,2024-05-19 10:37:00,2024-05-19 10:50:24,N,Manhattan,Midtown East,Yellow Zone,Manhattan,East Village,Yellow Zone,May,Sunday,10:37,10:50,Morining
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2024-03-07 06:57:34,2024-03-07 07:05:30,N,Manhattan,East Chelsea,Yellow Zone,Manhattan,Midtown Center,Yellow Zone,March,Thursday,06:57,07:05,Morining
19996,2024-03-12 09:38:33,2024-03-12 09:44:14,N,Manhattan,Midtown North,Yellow Zone,Manhattan,Midtown Center,Yellow Zone,March,Tuesday,09:38,09:44,Morining
19997,2024-02-20 14:07:41,2024-02-20 14:21:40,N,Manhattan,Lenox Hill East,Yellow Zone,Manhattan,Midtown South,Yellow Zone,February,Tuesday,14:07,14:21,Afternoon
19998,2024-05-16 16:01:32,2024-05-16 16:09:58,N,Manhattan,Midtown Center,Yellow Zone,Manhattan,Midtown South,Yellow Zone,May,Thursday,16:01,16:09,Afternoon
19999,2024-03-25 20:52:47,2024-03-25 21:09:02,N,Manhattan,Lenox Hill East,Yellow Zone,Manhattan,Upper West Side North,Yellow Zone,March,Monday,20:52,21:09,Evening